name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'

      - name: Build
        run: go build -v -o . ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rmadison
            rmadison-server
